* Great word
** The collars, the spats, the cufflinks, the bow tie, the hats. You dress for battle, in a way, that I don't, today.
Michael Stuhlbarg about his dressing in BoardWalk Empire.
** Он был, не как горный пейзаж на закате, а как ветер бросающийся в объятия.
Дмитрий Савитский "49 минут джаза" выпуск 332 http://ds.it.net.ua/prog/841
** Do more and more with less and less until eventually you can do everything with nothing.
Ephemeralization.
** Happiness is when what you think, what you say, and what you do are in harmony.
Mahatma Gandhi
** Try not to become a man of success, but rather try to become a man of value
Albert Einstein
* Fun
** Leave me in peace wizard
** Begone wizard
** Grease palming
Corruption.
** ... so cool your jets for now
** to make a silk purse out of a sow's ear
You can't create a fine product from inferior materials.
** If his mouth is moving - he is lying.
* Expressions
** Tongue and cheek
As a joke.
** When push comes to shove
A point when matters must be confronted, one way or another.
** Mathematical Gore Gallore - Mine
** Пердак в чердак - Mine
** There is not enought fun in my fun! - Mine
Print on a shirt:

#+begin_src lisp
(defun There-is-not-enought-fun-in-my-fun!
             ((((((()))))))
)
#+end_src
* Being wise is the art what to overlook.
